# to be completed
# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job-public-repo-ubuntu:
    #if: github.repository == 'AkeemSemper/PBML_Lab_1_Students'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Copy Environment Variables
        run: |
          echo "GH_PAT=${{ secrets.GH_PAT }}" >> $GITHUB_ENV
      
      - name: Open Original Repository
        if: github.repository == 'AkeemSemper/PBML_Lab_1_Students'
        uses: actions/checkout@v4
        with:
          repository: 'AkeemSemper/PBML_Lab_1_Students'
          ref: 'main'

          #token: ${{ secrets.GH_PAT }}
      - name: Open Assginment Repository
        if: github.repository_owner == 'AkeemSemperDataScience'
        uses: actions/checkout@v4
        with:
          repository: 'AkeemSemper/PBML_Lab_1_Students'
          ref: 'main'

          #token: ${{ secrets.GH_PAT }}
      - name: Check Rep
        run: |
          ls
          git status

      - name: Clone GuillaumeFalourd/poc-github-actions PRIVATE repository
        if: github.repository == 'AkeemSemper/PBML_Lab_1_Students'
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'AkeemSemper'
          repository: 'Programming_Basics_for_ML'
          access-token: ${{ secrets.GH_PAT }}

      - name: Access cloned repository content
        if: github.repository == 'AkeemSemper/PBML_Lab_1_Students' 
        run: |
          # Check Status
          #ls -rf

          # Copy all
          cp -r Programming_Basics_for_ML/course_material/labs/lab1/* .
          rm -f SAMP_SOL*
          #ls -la workbooks

          # Clear
          rm -rf Programming_Basics_for_ML

      #- name: Download other file
        #if: github.repository_owner == 'AkeemSemperDataScience'
        #run: |
          # Check Status
          #ls -rf

          # Copy all
          #cp -r Programming_Basics_for_ML/course_material/labs/lab1/* .
          #rm -f SAMP_SOL*
          #ls -la workbooks
#Test Grades
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test_4
        id: test_4
        uses: classroom-resources/autograding-python-grader@v1
        with:
          timeout: 10
          max-score: 5
          setup-command: pip install pandas pytest
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TEST_4_RESULTS: "${{steps.test_4.outputs.result}}"
        with:
          runners: test_4
#Push Changes
      - name: Commit and push changes
        if: github.repository == 'AkeemSemper/PBML_Lab_1_Students'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Generated Update from Main Repository"
          git push --force